const SUCCESS = 200;
const CREATE = 201;
const BAD_REQUEST = 400;
const INCORRECT = 401;
const REQUEST_DENIED = 403;
const NOT_FOUND = 404;
const REGISTRATION_ERROR = 409;
const DEFAULT = 500;
const ERROR = 11000;

module.exports = {
  SUCCESS,
  CREATE,
  BAD_REQUEST,
  INCORRECT,
  REQUEST_DENIED,
  NOT_FOUND,
  REGISTRATION_ERROR,
  DEFAULT,
  ERROR,
};
